In [1]:
# Import Libraries
import pandas as pd
import time
import random

# Webscrape Data

In [81]:
# Create a list of seasons 2014-2023
seasons = list(range(2014, 2024))
seasons

[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

In [89]:
# Create an empty list to store DataFrames for each season
dfs_per_season = []

# Iterate through seasons
for season in seasons:
    # Set URL
    url =  f'https://www.sports-reference.com/cfb/years/{season}-schedule.html'
    print(url)

    # Get game results ('id': 'schedule' is an HTML attribute on the website)
    results_df = pd.read_html(url, header=1, attrs={'id': 'schedule'})[0]

    # Append the dataframe to the list
    dfs_per_season.append(results_df)

    # Pause the program so don't get flagged by website
    time.sleep(random.randint(4,5))

dfs_per_season

https://www.sports-reference.com/cfb/years/2014-schedule.html
https://www.sports-reference.com/cfb/years/2015-schedule.html
https://www.sports-reference.com/cfb/years/2016-schedule.html
https://www.sports-reference.com/cfb/years/2017-schedule.html
https://www.sports-reference.com/cfb/years/2018-schedule.html
https://www.sports-reference.com/cfb/years/2019-schedule.html
https://www.sports-reference.com/cfb/years/2020-schedule.html
https://www.sports-reference.com/cfb/years/2021-schedule.html
https://www.sports-reference.com/cfb/years/2022-schedule.html
https://www.sports-reference.com/cfb/years/2023-schedule.html

[       1 1.1  Aug 27, 2014   7:00 PM  Wed       Georgia State   38 Unnamed: 7  \
 0      2   1  Aug 28, 2014   7:00 PM  Thu               Akron   41        NaN
 1      3   1  Aug 28, 2014  10:30 PM  Thu  (19) Arizona State   45        NaN
 2      4   1  Aug 28, 2014   7:00 PM  Thu    Central Michigan   20        NaN
 3      5   1  Aug 28, 2014   7:02 PM  Thu    Louisiana-Monroe   17        NaN
 4      6   1  Aug 28, 2014   7:00 PM  Thu           Minnesota   42        NaN
 ..   ...  ..           ...       ...  ...                 ...  ...        ...
 882  865  20   Jan 2, 2015   6:45 PM  Fri           (14) UCLA   40          N
 883  866  20   Jan 3, 2015  12:00 PM  Sat             Florida   28          N
 884  867  20   Jan 4, 2015   9:00 PM  Sun              Toledo   63          N
 885   Rk  Wk          Date      Time  Day              Winner  Pts        NaN
 886  868  21  Jan 12, 2015   8:30 PM  Mon      (5) Ohio State   42          N

      Abilene Christian   37                                        Unnamed: 10
 0               Howard    0                                                NaN
 1          Weber State   14                                                NaN
 2          Chattanooga   16                                                NaN
 3          Wake Forest   10                                                NaN
 4     Eastern Illinois   20                                                NaN
 ..                 ...  ...                                                ...
 882  (11) Kansas State   35                       Alamo Bowl (San Antonio, TX)
 883      East Carolina   20                   Birmingham Bowl (Birmingham, AL)
 884     Arkansas State   44                          GoDaddy Bowl (Mobile, AL)
 885              Loser  Pts                                              Notes
 886         (3) Oregon   20  College Football Playoff National Championship...

 [887 rows x 11 columns],
        1 1.1   Sep 3, 2015  10:00 PM  Thu           (22) Arizona   42  \
 0      2   1   Sep 3, 2015   7:00 PM  Thu             Ball State   48
 1      3   1   Sep 3, 2015   7:30 PM  Thu            Connecticut   20
 2      4   1   Sep 3, 2015   9:30 PM  Thu                   Duke   37
 3      5   1   Sep 3, 2015   6:00 PM  Thu  Florida International   15
 4      6   1   Sep 3, 2015       NaN  Thu           Fresno State   34
 ..   ...  ..           ...       ...  ...                    ...  ...
 883  868  18   Jan 2, 2016  12:00 PM  Sat                Georgia   24
 884  869  18   Jan 2, 2016   6:45 PM  Sat   (11) Texas Christian   47
 885  870  18   Jan 2, 2016  10:15 PM  Sat          West Virginia   43
 886   Rk  Wk          Date      Time  Day                 Winner  Pts
 887  871  19  Jan 11, 2016   8:30 PM  Mon            (2) Alabama   45

     Unnamed: 7            Texas-San Antonio   32  \
 0          NaN  Virginia Military Institute   36
 1          NaN                    Villanova   15
 2            @                       Tulane    7
 3            @              Central Florida   14
 4          NaN            Abilene Christian   13
 ..         ...                          ...  ...
 883          N                   Penn State   17
 884          N                  (15) Oregon   41
 885          N                Arizona State   42
 886        NaN                        Loser  Pts
 887          N                  (1) Clemson   40

                                            Unnamed: 10
 0                                                  NaN
 1                                                  NaN
 2                                                  NaN
 3                                                  NaN
 4                                                  NaN
 ..                                                 ...
 883                  TaxSlayer Bowl (Jacksonville, FL)
 884                       Alamo Bowl (San Antonio, TX)
 885                            Cactus Bowl (Tempe, AZ)
 886                                              Notes
 887  College Football Playoff National Championship...

 [888 rows x 11 columns],
        1 1.1 Aug 26, 2016 10:00 PM  Fri               California   51    N  \
 0     Rk  Wk         Date     Time  Day                   Winner  Pts  NaN
 1      2   2  Sep 1, 2016  7:00 PM  Thu         Central Michigan   49  NaN
 2      3   2  Sep 1, 2016  7:00 PM  Thu               Cincinnati   28  NaN
 3      4   2  Sep 1, 2016  7:00 PM  Thu              Connecticut   24  NaN
 4      5   2  Sep 1, 2016  9:00 PM  Thu                    Idaho   20  NaN
 ..   ...  ..          ...      ...  ...                      ...  ...  ...
 887  870  20  Jan 2, 2017  8:50 PM  Mon             (7) Oklahoma   35    N
 888  871  20  Jan 2, 2017  5:00 PM  Mon  (9) Southern California   52    N
 889  872  20  Jan 2, 2017  1:00 PM  Mon            (8) Wisconsin   24    N
 890   Rk  Wk         Date     Time  Day                   Winner  Pts  NaN
 891  873  21  Jan 9, 2017  8:00 PM  Mon              (3) Clemson   35    N

                     Hawaii   31  \
 0                    Loser  Pts
 1             Presbyterian    3
 2         Tennessee-Martin    7
 3                    Maine   21
 4            Montana State   17
 ..                     ...  ...
 887            (17) Auburn   19
 888         (5) Penn State   49
 889  (12) Western Michigan   16
 890                  Loser  Pts
 891            (1) Alabama   31

                              ANZ Stadium - Sydney, AUS
 0                                                Notes
 1      Kelly/Shorts Stadium - Mount Pleasant, Michigan
 2                   Nippert Stadium - Cincinnati, Ohio
 3        Rentschler Field - East Hartford, Connecticut
 4                          Kibbie Dome - Moscow, Idaho
 ..                                                 ...
 887  Sugar Bowl (Mercedes-Benz Superdome - New Orle...
 888                           Rose Bowl (Pasadena, CA)
 889      Cotton Bowl (AT&T Stadium - Arlington, Texas)
 890                                              Notes
 891  College Football Playoff National Championship...

 [892 rows x 11 columns],
        1 1.1  Aug 26, 2017 Unnamed: 3  Sat       Brigham Young   20  \
 0      2   1  Aug 26, 2017    2:30 PM  Sat      Colorado State   58
 1      3   1  Aug 26, 2017    6:00 PM  Sat              Hawaii   38
 2      4   1  Aug 26, 2017    7:30 PM  Sat  (19) South Florida   42
 3      5   1  Aug 26, 2017   10:00 PM  Sat       (14) Stanford   62
 4     Rk  Wk          Date       Time  Day              Winner  Pts
 ..   ...  ..           ...        ...  ...                 ...  ...
 888  871  20   Jan 1, 2018    5:00 PM  Mon         (3) Georgia   54
 889  872  20   Jan 1, 2018    1:00 PM  Mon     (14) Notre Dame   21
 890  873  20   Jan 1, 2018   12:00 PM  Mon      South Carolina   26
 891   Rk  Wk          Date       Time  Day              Winner  Pts
 892  874  21   Jan 8, 2018    8:00 PM  Mon         (4) Alabama   26

     Unnamed: 7        Portland State    6  \
 0          NaN          Oregon State   27
 1            @         Massachusetts   35
 2            @        San Jose State   22
 3            N                  Rice    7
 4          NaN                 Loser  Pts
 ..         ...                   ...  ...
 888          N          (2) Oklahoma   48
 889          N  (16) Louisiana State   17
 890          N              Michigan   19
 891        NaN                 Loser  Pts
 892          N           (3) Georgia   23

                   LaVell Edwards Stadium - Provo, Utah
 0    Sonny Lubrick Field at Colorado State Stadium ...
 1    Warren McGuirk Alumni Stadium - Amherst, Massa...
 2                 CEFCU Stadium - San Jose, California
 3                        Allianz Stadium - Sydney, AUS
 4                                                Notes
 ..                                                 ...
 888       Rose Bowl (Rose Bowl - Pasadena, California)
 889  Citrus Bowl (Camping World Stadium - Orlando, ...
 890  Outback Bowl (Raymond James Stadium - Tampa, F...
 891                                              Notes
 892  College Football Playoff National Championship...

 [893 rows x 11 columns],
        1 1.1  Aug 25, 2018   7:30 PM  Sat                Hawaii   43    @  \
 0      2   1  Aug 25, 2018   5:30 PM  Sat         Massachusetts   63  NaN
 1      3   1  Aug 25, 2018   7:00 PM  Sat                  Rice   31  NaN
 2      4   1  Aug 25, 2018  10:00 PM  Sat               Wyoming   29    @
 3     Rk  Wk          Date      Time  Day                Winner  Pts  NaN
 4      5   2  Aug 30, 2018   8:00 PM  Thu    Alabama-Birmingham   52  NaN
 ..   ...  ..           ...       ...  ...                   ...  ...  ...
 898  880  21   Jan 1, 2019   1:00 PM  Tue         (16) Kentucky   27    N
 899  881  21   Jan 1, 2019   1:00 PM  Tue  (11) Louisiana State   40    N
 900  882  21   Jan 1, 2019   5:00 PM  Tue        (5) Ohio State   28    N
 901  883  21   Jan 1, 2019   8:45 PM  Tue            (14) Texas   28    N
 902  884  21   Jan 7, 2019   8:00 PM  Mon           (2) Clemson   44    N

           Colorado State   34  \
 0               Duquesne   15
 1       Prairie View A&M   28
 2       New Mexico State    7
 3                  Loser  Pts
 4         Savannah State    0
 ..                   ...  ...
 898      (13) Penn State   24
 899  (7) Central Florida   32
 900       (9) Washington   23
 901          (6) Georgia   21
 902          (1) Alabama   16

     Sonny Lubick Field at Canvas Stadium - Fort Collins, Colorado
 0    Warren McGuirk Alumni Stadium - Amherst, Massa...
 1                        Rice Stadium - Houston, Texas
 2      Aggie Memorial Stadium - Las Cruces, New Mexico
 3                                                Notes
 4                   Legion Field - Birmingham, Alabama
 ..                                                 ...
 898  Citrus Bowl (Camping World Stadium - Orlando, ...
 899  Fiesta Bowl (State Farm Stadium - Glendale, Ar...
 900       Rose Bowl (Rose Bowl - Pasadena, California)
 901  Sugar Bowl (Mercedes-Benz Superdome - New Orle...
 902  College Football Playoff National Championship...

 [903 rows x 11 columns],
        1 1.1  Aug 24, 2019 Unnamed: 3  Sat          (8) Florida   24    N  \
 0      2   1  Aug 24, 2019        NaN  Sat               Hawaii   45  NaN
 1     Rk  Wk          Date       Time  Day               Winner  Pts  NaN
 2      3   2  Aug 29, 2019        NaN  Thu   Alabama-Birmingham   24  NaN
 3      4   2  Aug 29, 2019        NaN  Thu        Arizona State   30  NaN
 4      5   2  Aug 29, 2019        NaN  Thu        Bowling Green   46  NaN
 ..   ...  ..           ...        ...  ...                  ...  ...  ...
 903  885  21   Jan 3, 2020        NaN  Fri                 Ohio   30    N
 904  886  21   Jan 4, 2020        NaN  Sat               Tulane   30    N
 905  887  21   Jan 6, 2020        NaN  Mon            Louisiana   27    N
 906   Rk  Wk          Date       Time  Day               Winner  Pts  NaN
 907  888  22  Jan 13, 2020        NaN  Mon  (1) Louisiana State   42    N

                Miami (FL)   20  \
 0                 Arizona   38
 1                   Loser  Pts
 2           Alabama State   19
 3              Kent State    7
 4            Morgan State    3
 ..                    ...  ...
 903                Nevada   21
 904  Southern Mississippi   13
 905            Miami (OH)   17
 906                 Loser  Pts
 907           (3) Clemson   25

               Camping World Stadium - Orlando, Florida
 0                     Aloha Stadium - Honolulu, Hawaii
 1                                                Notes
 2                   Legion Field - Birmingham, Alabama
 3                   Sun Devil Stadium - Tempe, Arizona
 4             Doyt Perry Stadium - Bowling Green, Ohio
 ..                                                 ...
 903  Famous Idaho Potato Bowl (Albertsons Stadium -...
 904  Armed Forces Bowl (Amon G. Carter Stadium - Fo...
 905  LendingTree Bowl (Ladd-Peebles Stadium - Mobil...
 906                                              Notes
 907  College Football Playoff National Championship...

 [908 rows x 11 columns],
        1 1.1   Sep 3, 2020  8:00 PM  Thu Alabama-Birmingham   45 Unnamed: 7  \
 0      2   1   Sep 3, 2020  8:00 PM  Thu      South Alabama   32          @
 1      3   1   Sep 5, 2020  1:30 PM  Sat               Army   42        NaN
 2      4   1   Sep 5, 2020  1:00 PM  Sat           Marshall   59        NaN
 3      5   1   Sep 5, 2020  8:00 PM  Sat            Memphis   37        NaN
 4      6   1   Sep 5, 2020  7:30 PM  Sat        North Texas   57        NaN
 ..   ...  ..           ...      ...  ...                ...  ...        ...
 584  568  19  Jan 11, 2021  8:00 PM  Mon        (1) Alabama   52          N
 585   Rk  Wk          Date     Time  Day             Winner  Pts        NaN
 586  569  20  Feb 21, 2021  5:00 PM  Sun     Tarleton State   43          @
 587   Rk  Wk          Date     Time  Day             Winner  Pts        NaN
 588  570  21   Mar 7, 2021  5:00 PM  Sun   New Mexico State   36          N

            Central Arkansas   35  \
 0      Southern Mississippi   21
 1    Middle Tennessee State    0
 2          Eastern Kentucky    0
 3            Arkansas State   24
 4           Houston Baptist   31
 ..                      ...  ...
 584          (3) Ohio State   24
 585                   Loser  Pts
 586        New Mexico State   17
 587                   Loser  Pts
 588             Dixie State   29

                                            Unnamed: 10
 0                                                  NaN
 1                                                  NaN
 2                                                  NaN
 3                                                  NaN
 4                                                  NaN
 ..                                                 ...
 584  College Football Playoff National Championship...
 585                                              Notes
 586    Aggie Memorial Stadium - Las Cruces, New Mexico
 587                                              Notes
 588                          Sun Bowl - El Paso, Texas

 [589 rows x 11 columns],
        1 1.1  Aug 28, 2021   2:00 PM  Sat        Fresno State   45 Unnamed: 7  \
 0      2   1  Aug 28, 2021   1:20 PM  Sat            Illinois   30        NaN
 1      3   1  Aug 28, 2021  10:00 PM  Sat      San Jose State   45        NaN
 2      4   1  Aug 28, 2021   9:30 PM  Sat       Texas-El Paso   30          @
 3      5   1  Aug 28, 2021   3:30 PM  Sat                UCLA   44        NaN
 4     Rk  Wk          Date      Time  Day              Winner  Pts        NaN
 ..   ...  ..           ...       ...  ...                 ...  ...        ...
 900  884  19   Jan 1, 2022   5:00 PM  Sat      (7) Ohio State   48          N
 901  885  19   Jan 1, 2022   1:00 PM  Sat  (9) Oklahoma State   37          N
 902   Rk  Wk          Date      Time  Day              Winner  Pts        NaN
 903  886  20   Jan 4, 2022   9:00 PM  Tue        Kansas State   42          N
 904  887  20  Jan 10, 2022   8:00 PM  Mon         (3) Georgia   33          N

           Connecticut    0                                        Unnamed: 10
 0            Nebraska   22                                                NaN
 1       Southern Utah   14                                                NaN
 2    New Mexico State    3                                                NaN
 3              Hawaii   10                                                NaN
 4               Loser  Pts                                              Notes
 ..                ...  ...                                                ...
 900         (10) Utah   45       Rose Bowl (Rose Bowl - Pasadena, California)
 901    (5) Notre Dame   35  Fiesta Bowl (State Farm Stadium - Glendale, Ar...
 902             Loser  Pts                                              Notes
 903   Louisiana State   20          Texas Bowl (NRG Stadium - Houston, Texas)
 904       (1) Alabama   18  College Football Playoff National Championship...

 [905 rows x 11 columns],
        1 1.1  Aug 27, 2022   7:00 PM  Sat        Florida Atlantic   43  \
 0      2   1  Aug 27, 2022   5:00 PM  Sat           Florida State   47
 1      3   1  Aug 27, 2022   4:00 PM  Sat                Illinois   38
 2      4   1  Aug 27, 2022  10:00 PM  Sat                  Nevada   23
 3      5   1  Aug 27, 2022   3:30 PM  Sat        Nevada-Las Vegas   52
 4      6   1  Aug 27, 2022   8:00 PM  Sat          North Carolina   56
 ..   ...  ..           ...       ...  ...                     ...  ...
 910  893  20   Jan 2, 2023  12:00 PM  Mon  (24) Mississippi State   19
 911  894  20   Jan 2, 2023   5:00 PM  Mon          (9) Penn State   35
 912  895  20   Jan 2, 2023   1:00 PM  Mon             (14) Tulane   46
 913   Rk  Wk          Date      Time  Day                  Winner  Pts
 914  896  21   Jan 9, 2023   7:30 PM  Mon             (1) Georgia   65

     Unnamed: 7                Charlotte   13  \
 0          NaN                 Duquesne    7
 1          NaN                  Wyoming    6
 2            @         New Mexico State   12
 3          NaN              Idaho State   21
 4          NaN              Florida A&M   24
 ..         ...                      ...  ...
 910          N                 Illinois   10
 911          N                 (7) Utah   21
 912          N  (8) Southern California   45
 913        NaN                    Loser  Pts
 914          N      (3) Texas Christian    7

                                         Unnamed: 10
 0                                               NaN
 1                                               NaN
 2                                               NaN
 3                                               NaN
 4                                               NaN
 ..                                              ...
 910                                 ReliaQuest Bowl
 911                                       Rose Bowl
 912                                     Cotton Bowl
 913                                           Notes
 914  College Football Playoff National Championship

 [915 rows x 11 columns],
        1 1.1  Aug 26, 2023   5:30 PM  Sat       Jacksonville State   17  \
 0      2   1  Aug 26, 2023   9:00 PM  Sat           Louisiana Tech   22
 1      3   1  Aug 26, 2023   7:00 PM  Sat            Massachusetts   41
 2      4   1  Aug 26, 2023   2:30 PM  Sat          (13) Notre Dame   42
 3      5   1  Aug 26, 2023   7:00 PM  Sat          San Diego State   20
 4      6   1  Aug 26, 2023   8:00 PM  Sat  (6) Southern California   56
 ..   ...  ..           ...       ...  ...                      ...  ...
 922  905  20   Jan 1, 2024   5:00 PM  Mon              (5) Alabama  NaN
 923  906  20   Jan 1, 2024   1:00 PM  Mon                (20) Iowa  NaN
 924  907  20   Jan 1, 2024   1:00 PM  Mon             (18) Liberty  NaN
 925  908  20   Jan 1, 2024   9:45 PM  Mon                (3) Texas  NaN
 926  909  20   Jan 1, 2024  12:00 PM  Mon                Wisconsin  NaN

     Unnamed: 7          Texas-El Paso   14      Unnamed: 10
 0          NaN  Florida International   17              NaN
 1            @       New Mexico State   30              NaN
 2            N                   Navy    3              NaN
 3          NaN                   Ohio   13              NaN
 4          NaN         San Jose State   28              NaN
 ..         ...                    ...  ...              ...
 922          N           (1) Michigan  NaN        Rose Bowl
 923          N         (25) Tennessee  NaN      Citrus Bowl
 924          N             (8) Oregon  NaN      Fiesta Bowl
 925          N         (2) Washington  NaN       Sugar Bowl
 926          N   (13) Louisiana State  NaN  ReliaQuest Bowl

 [927 rows x 11 columns]]

In [90]:
# Loop through each DataFrame in the list 
for i, df in enumerate(dfs_per_season):
    print(f"DataFrame for Season {seasons[i]}:")
    print(df.head())  # Display the first few rows of each DataFrame
    print("\n" + "-"*40 + "\n")

DataFrame for Season 2014:
   1 1.1  Aug 27, 2014   7:00 PM  Wed       Georgia State  38 Unnamed: 7  \
0  2   1  Aug 28, 2014   7:00 PM  Thu               Akron  41        NaN
1  3   1  Aug 28, 2014  10:30 PM  Thu  (19) Arizona State  45        NaN
2  4   1  Aug 28, 2014   7:00 PM  Thu    Central Michigan  20        NaN
3  5   1  Aug 28, 2014   7:02 PM  Thu    Louisiana-Monroe  17        NaN
4  6   1  Aug 28, 2014   7:00 PM  Thu           Minnesota  42        NaN

  Abilene Christian  37 Unnamed: 10
0            Howard   0         NaN
1       Weber State  14         NaN
2       Chattanooga  16         NaN
3       Wake Forest  10         NaN
4  Eastern Illinois  20         NaN

----------------------------------------

DataFrame for Season 2015:
   1 1.1  Sep 3, 2015 10:00 PM  Thu           (22) Arizona  42 Unnamed: 7  \
0  2   1  Sep 3, 2015  7:00 PM  Thu             Ball State  48        NaN
1  3   1  Sep 3, 2015  7:30 PM  Thu            Connecticut  20        NaN
2  4   1  Sep 3, 2015  9:30 PM  Thu                   Duke  37          @
3  5   1  Sep 3, 2015  6:00 PM  Thu  Florida International  15          @
4  6   1  Sep 3, 2015      NaN  Thu           Fresno State  34        NaN

             Texas-San Antonio  32 Unnamed: 10
0  Virginia Military Institute  36         NaN
1                    Villanova  15         NaN
2                       Tulane   7         NaN
3              Central Florida  14         NaN
4            Abilene Christian  13         NaN

----------------------------------------

DataFrame for Season 2016:
    1 1.1 Aug 26, 2016 10:00 PM  Fri        California   51    N  \
0  Rk  Wk         Date     Time  Day            Winner  Pts  NaN
1   2   2  Sep 1, 2016  7:00 PM  Thu  Central Michigan   49  NaN
2   3   2  Sep 1, 2016  7:00 PM  Thu        Cincinnati   28  NaN
3   4   2  Sep 1, 2016  7:00 PM  Thu       Connecticut   24  NaN
4   5   2  Sep 1, 2016  9:00 PM  Thu             Idaho   20  NaN

             Hawaii   31                        ANZ Stadium - Sydney, AUS
0             Loser  Pts                                            Notes
1      Presbyterian    3  Kelly/Shorts Stadium - Mount Pleasant, Michigan
2  Tennessee-Martin    7               Nippert Stadium - Cincinnati, Ohio
3             Maine   21    Rentschler Field - East Hartford, Connecticut
4     Montana State   17                      Kibbie Dome - Moscow, Idaho

----------------------------------------

DataFrame for Season 2017:
    1 1.1  Aug 26, 2017 Unnamed: 3  Sat       Brigham Young   20 Unnamed: 7  \
0   2   1  Aug 26, 2017    2:30 PM  Sat      Colorado State   58        NaN
1   3   1  Aug 26, 2017    6:00 PM  Sat              Hawaii   38          @
2   4   1  Aug 26, 2017    7:30 PM  Sat  (19) South Florida   42          @
3   5   1  Aug 26, 2017   10:00 PM  Sat       (14) Stanford   62          N
4  Rk  Wk          Date       Time  Day              Winner  Pts        NaN

   Portland State    6               LaVell Edwards Stadium - Provo, Utah
0    Oregon State   27  Sonny Lubrick Field at Colorado State Stadium ...
1   Massachusetts   35  Warren McGuirk Alumni Stadium - Amherst, Massa...
2  San Jose State   22               CEFCU Stadium - San Jose, California
3            Rice    7                      Allianz Stadium - Sydney, AUS
4           Loser  Pts                                              Notes

----------------------------------------

DataFrame for Season 2018:
    1 1.1  Aug 25, 2018   7:30 PM  Sat              Hawaii   43    @  \
0   2   1  Aug 25, 2018   5:30 PM  Sat       Massachusetts   63  NaN
1   3   1  Aug 25, 2018   7:00 PM  Sat                Rice   31  NaN
2   4   1  Aug 25, 2018  10:00 PM  Sat             Wyoming   29    @
3  Rk  Wk          Date      Time  Day              Winner  Pts  NaN
4   5   2  Aug 30, 2018   8:00 PM  Thu  Alabama-Birmingham   52  NaN

     Colorado State   34  \
0          Duquesne   15
1  Prairie View A&M   28
2  New Mexico State    7
3             Loser  Pts
4    Savannah State    0

  Sonny Lubick Field at Canvas Stadium - Fort Collins, Colorado
0  Warren McGuirk Alumni Stadium - Amherst, Massa...
1                      Rice Stadium - Houston, Texas
2    Aggie Memorial Stadium - Las Cruces, New Mexico
3                                              Notes
4                 Legion Field - Birmingham, Alabama

----------------------------------------

DataFrame for Season 2019:
    1 1.1  Aug 24, 2019 Unnamed: 3  Sat         (8) Florida   24    N  \
0   2   1  Aug 24, 2019        NaN  Sat              Hawaii   45  NaN
1  Rk  Wk          Date       Time  Day              Winner  Pts  NaN
2   3   2  Aug 29, 2019        NaN  Thu  Alabama-Birmingham   24  NaN
3   4   2  Aug 29, 2019        NaN  Thu       Arizona State   30  NaN
4   5   2  Aug 29, 2019        NaN  Thu       Bowling Green   46  NaN

      Miami (FL)   20  Camping World Stadium - Orlando, Florida
0        Arizona   38          Aloha Stadium - Honolulu, Hawaii
1          Loser  Pts                                     Notes
2  Alabama State   19        Legion Field - Birmingham, Alabama
3     Kent State    7        Sun Devil Stadium - Tempe, Arizona
4   Morgan State    3  Doyt Perry Stadium - Bowling Green, Ohio

----------------------------------------

DataFrame for Season 2020:
   1 1.1  Sep 3, 2020  8:00 PM  Thu Alabama-Birmingham  45 Unnamed: 7  \
0  2   1  Sep 3, 2020  8:00 PM  Thu      South Alabama  32          @
1  3   1  Sep 5, 2020  1:30 PM  Sat               Army  42        NaN
2  4   1  Sep 5, 2020  1:00 PM  Sat           Marshall  59        NaN
3  5   1  Sep 5, 2020  8:00 PM  Sat            Memphis  37        NaN
4  6   1  Sep 5, 2020  7:30 PM  Sat        North Texas  57        NaN

         Central Arkansas  35 Unnamed: 10
0    Southern Mississippi  21         NaN
1  Middle Tennessee State   0         NaN
2        Eastern Kentucky   0         NaN
3          Arkansas State  24         NaN
4         Houston Baptist  31         NaN

----------------------------------------

DataFrame for Season 2021:
    1 1.1  Aug 28, 2021   2:00 PM  Sat    Fresno State   45 Unnamed: 7  \
0   2   1  Aug 28, 2021   1:20 PM  Sat        Illinois   30        NaN
1   3   1  Aug 28, 2021  10:00 PM  Sat  San Jose State   45        NaN
2   4   1  Aug 28, 2021   9:30 PM  Sat   Texas-El Paso   30          @
3   5   1  Aug 28, 2021   3:30 PM  Sat            UCLA   44        NaN
4  Rk  Wk          Date      Time  Day          Winner  Pts        NaN

        Connecticut    0 Unnamed: 10
0          Nebraska   22         NaN
1     Southern Utah   14         NaN
2  New Mexico State    3         NaN
3            Hawaii   10         NaN
4             Loser  Pts       Notes

----------------------------------------

DataFrame for Season 2022:
   1 1.1  Aug 27, 2022   7:00 PM  Sat  Florida Atlantic  43 Unnamed: 7  \
0  2   1  Aug 27, 2022   5:00 PM  Sat     Florida State  47        NaN
1  3   1  Aug 27, 2022   4:00 PM  Sat          Illinois  38        NaN
2  4   1  Aug 27, 2022  10:00 PM  Sat            Nevada  23          @
3  5   1  Aug 27, 2022   3:30 PM  Sat  Nevada-Las Vegas  52        NaN
4  6   1  Aug 27, 2022   8:00 PM  Sat    North Carolina  56        NaN

          Charlotte  13 Unnamed: 10
0          Duquesne   7         NaN
1           Wyoming   6         NaN
2  New Mexico State  12         NaN
3       Idaho State  21         NaN
4       Florida A&M  24         NaN

----------------------------------------

DataFrame for Season 2023:
   1 1.1  Aug 26, 2023  5:30 PM  Sat       Jacksonville State  17 Unnamed: 7  \
0  2   1  Aug 26, 2023  9:00 PM  Sat           Louisiana Tech  22        NaN
1  3   1  Aug 26, 2023  7:00 PM  Sat            Massachusetts  41          @
2  4   1  Aug 26, 2023  2:30 PM  Sat          (13) Notre Dame  42          N
3  5   1  Aug 26, 2023  7:00 PM  Sat          San Diego State  20        NaN
4  6   1  Aug 26, 2023  8:00 PM  Sat  (6) Southern California  56        NaN

           Texas-El Paso  14 Unnamed: 10
0  Florida International  17         NaN
1       New Mexico State  30         NaN
2                   Navy   3         NaN
3                   Ohio  13         NaN
4         San Jose State  28         NaN

----------------------------------------

# Clean Data

In [91]:
# Look at seasons (adjust index to see specific season)
df_season = dfs_per_season[5]
df_season.head()

,1,1.1,"Aug 24, 2019",Unnamed: 3,Sat,(8) Florida,24,N,Miami (FL),20,"Camping World Stadium - Orlando, Florida"
0,2,1,"Aug 24, 2019",NaN,Sat,Hawaii,45,NaN,Arizona,38,"Aloha Stadium - Honolulu, Hawaii"
1,Rk,Wk,Date,Time,Day,Winner,Pts,NaN,Loser,Pts,Notes
2,3,2,"Aug 29, 2019",NaN,Thu,Alabama-Birmingham,24,NaN,Alabama State,19,"Legion Field - Birmingham, Alabama"
3,4,2,"Aug 29, 2019",NaN,Thu,Arizona State,30,NaN,Kent State,7,"Sun Devil Stadium - Tempe, Arizona"
4,5,2,"Aug 29, 2019",NaN,Thu,Bowling Green,46,NaN,Morgan State,3,"Doyt Perry Stadium - Bowling Green, Ohio"

In [92]:
# Clean data for each DataFrame using loop
for i, season_df in enumerate(dfs_per_season):
    # Add columns
    season_df.columns = ['Rk', 'Wk', 'Date', 'Time', 'Day', 'Winner', 'Winner Pts', '?', 'Loser', 'Loser Pts', 'Notes']

    # Drop unnecssary columns
    season_df.drop(['Rk', 'Day', '?', 'Notes'], axis=1, inplace=True)

    # Convert 'Winner Pts' and 'Loser Pts' to numeric
    season_df['Winner Pts'] = pd.to_numeric(season_df['Winner Pts'], errors='coerce')
    season_df['Loser Pts'] = pd.to_numeric(season_df['Loser Pts'], errors='coerce')

    # Find rows with NaN values (these are from the original dataset so take them out)
    rows_with_nan = season_df[season_df.isna().any(axis=1)]

    # Remove rows with NaN values
    season_df = season_df.dropna()

    # Standardize the winner and loser names (remove rankings)
    season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
    season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')

    # Insert Season into the dataframe
    season_df.insert(loc=0, column='Season', value=seasons[i])
    dfs_per_season[i] = season_df

    # Combine the date and time columns into a single column 'DateTime'
    season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])

    # Drop original 'Date' and 'Time' columns
    season_df = season_df.drop(['Date', 'Time'], axis=1)
    dfs_per_season[i] = season_df

    # Update the dataframe in the list
    dfs_per_season[i] = season_df

/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Winner'] = season_df['Winner'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['Loser'] = season_df['Loser'].str.replace(r'\(\d+\)\s*', '')
/var/folders/zm/fr635kq51d35fklpj2hv3s240000gn/T/ipykernel_7086/4128977209.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_df['DateTime'] = pd.to_datetime(season_df['Date'] + ' ' + season_df['Time'])

In [94]:
# Check to make sure the cleaning worked (adjust index to see different seasons)
df_season = dfs_per_season[4]
df_season.head()

,Season,Wk,Winner,Winner Pts,Loser,Loser Pts,DateTime
0,2018,1,Massachusetts,63.0,Duquesne,15.0,2018-08-25 17:30:00
1,2018,1,Rice,31.0,Prairie View A&M,28.0,2018-08-25 19:00:00
2,2018,1,Wyoming,29.0,New Mexico State,7.0,2018-08-25 22:00:00
4,2018,2,Alabama-Birmingham,52.0,Savannah State,0.0,2018-08-30 20:00:00
5,2018,2,Ball State,42.0,Central Connecticut State,6.0,2018-08-30 19:00:00

In [100]:
# Concatenate dataframes
combined_df = pd.concat(dfs_per_season, ignore_index=True)
combined_df

,Season,Wk,Winner,Winner Pts,Loser,Loser Pts,DateTime
0,2014,1,Akron,41.0,Howard,0.0,2014-08-28 19:00:00
1,2014,1,Arizona State,45.0,Weber State,14.0,2014-08-28 22:30:00
2,2014,1,Central Michigan,20.0,Chattanooga,16.0,2014-08-28 19:00:00
3,2014,1,Louisiana-Monroe,17.0,Wake Forest,10.0,2014-08-28 19:02:00
4,2014,1,Minnesota,42.0,Eastern Illinois,20.0,2014-08-28 19:00:00
...,...,...,...,...,...,...,...
7396,2023,15,Michigan,26.0,Iowa,0.0,2023-12-02 20:00:00
7397,2023,15,Southern Methodist,26.0,Tulane,14.0,2023-12-02 16:00:00
7398,2023,15,Texas,49.0,Oklahoma State,21.0,2023-12-02 12:00:00
7399,2023,15,Troy,49.0,Appalachian State,23.0,2023-12-02 16:00:00
7400,2023,16,Army,17.0,Navy,11.0,2023-12-09 15:00:00

# Restructure Data

In [97]:
# Duplicate the Dataframe
df_duplicated = combined_df.copy()

# Swap the information between 'Winner' and 'Loser' columns in the duplicated dataframe
df_duplicated[['Winner', 'Winner Pts', 'Loser', 'Loser Pts']] = combined_df[['Loser', 'Loser Pts', 'Winner', 'Winner Pts']]

# Add a new column 'Win' to indicate if team won (true) or lost (false)
df_duplicated['Win'] = False
combined_df['Win'] = True

# Concatenate the original and duplicated DataFrames
reshaped_df = pd.concat([combined_df, df_duplicated], ignore_index=True)

# Rename columns
reshaped_df = reshaped_df.rename(columns={'Winner': 'Team',
                                        'Winner Pts': 'Points Scored', 
                                        'Loser': 'Opponent', 
                                        'Loser Pts': 'Points Allowed'})

reshaped_df

,Season,Wk,Team,Points Scored,Opponent,Points Allowed,DateTime,Win
0,2014,1,Akron,41.0,Howard,0.0,2014-08-28 19:00:00,True
1,2014,1,Arizona State,45.0,Weber State,14.0,2014-08-28 22:30:00,True
2,2014,1,Central Michigan,20.0,Chattanooga,16.0,2014-08-28 19:00:00,True
3,2014,1,Louisiana-Monroe,17.0,Wake Forest,10.0,2014-08-28 19:02:00,True
4,2014,1,Minnesota,42.0,Eastern Illinois,20.0,2014-08-28 19:00:00,True
...,...,...,...,...,...,...,...,...
14797,2023,15,Iowa,0.0,Michigan,26.0,2023-12-02 20:00:00,False
14798,2023,15,Tulane,14.0,Southern Methodist,26.0,2023-12-02 16:00:00,False
14799,2023,15,Oklahoma State,21.0,Texas,49.0,2023-12-02 12:00:00,False
14800,2023,15,Appalachian State,23.0,Troy,49.0,2023-12-02 16:00:00,False
14801,2023,16,Navy,11.0,Army,17.0,2023-12-09 15:00:00,False

In [101]:
# Sort data by DateTime so everything is synchronized
df = reshaped_df.sort_values("DateTime")
df = df.reset_index(drop=True)
df

,Season,Wk,Team,Points Scored,Opponent,Points Allowed,DateTime,Win
0,2014,1,South Carolina,28.0,Texas A&M,52.0,2014-08-28 18:00:00,False
1,2014,1,Texas A&M,52.0,South Carolina,28.0,2014-08-28 18:00:00,True
2,2014,1,Akron,41.0,Howard,0.0,2014-08-28 19:00:00,True
3,2014,1,Central Michigan,20.0,Chattanooga,16.0,2014-08-28 19:00:00,True
4,2014,1,Presbyterian,3.0,Northern Illinois,55.0,2014-08-28 19:00:00,False
...,...,...,...,...,...,...,...,...
14797,2023,15,Florida State,16.0,Louisville,6.0,2023-12-02 20:00:00,True
14798,2023,15,Louisville,6.0,Florida State,16.0,2023-12-02 20:00:00,False
14799,2023,15,Iowa,0.0,Michigan,26.0,2023-12-02 20:00:00,False
14800,2023,16,Army,17.0,Navy,11.0,2023-12-09 15:00:00,True
14801,2023,16,Navy,11.0,Army,17.0,2023-12-09 15:00:00,False

In [99]:
# Export CSV 
df.to_csv('cfb.csv', index=False, na_rep='NA', encoding='utf-8')